# fly.toml app configuration file generated for gvs-matchbot on 2026-10-02T19:51:05Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'gvs-matchbot'
primary_region = 'sin'

[build]

[env]
TIME_CARD_DELETE = "14400"
DEFAULT_LANG = "km"

[[vm]]
memory = "256mb"
cpu_kind = "shared"
cpus = 1
